apiVersion: v1
kind: PersistentVolume
metadata:
  name: bai-elasticsearch-data-1
spec:
  storageClassName: "bai-elasticsearch-pv"
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/bai-elasticsearch-data-1
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bai-elasticsearch-master-1
spec:
  storageClassName: "bai-elasticsearch-pv"
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/bai-elasticsearch-master-1
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minikube-bai-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/bai
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: bai
    name: minikube-bai-pvc
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minikube-bai-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
