apiVersion: icp4a.ibm.com/v1
kind: ICP4ACluster
metadata:
  name: demo-template
  labels:
    app.kubernetes.io/instance: ibm-dba
    app.kubernetes.io/managed-by: ibm-dba
    app.kubernetes.io/name: ibm-dba
    release: 20.0.1
spec:
  appVersion: 20.0.1
  #####################################################################
  ## IBM Business Automation Studio 20.0.1 configuration ##
  #####################################################################
  bastudio_configuration:
    admin_secret_name: bastudio-admin-secret
    admin_user: <your default administrator ID>
    images:
      bastudio:
        repository: cp.icr.io/cp/cp4a/bas/bastudio
        tag: 20.0.1
    hostname:  <your external BAStudio host name>
    port: 443
    database:
      host: <database host name>
      # The database provided should be created by the BAStudio SQL script template.
      name: <database name>
      port: <database port>
      # If you want to enable database automatic client reroute (ACR) for HADR, you must configure alternative_host and alternative_port. Otherwise, leave them blank.
      alternative_host:
      alternative_port:
      type: db2
    jms_server:
      image:
        repository: cp.icr.io/cp/cp4a/bas/jms
        tag: 20.0.1
    #-----------------------------------------------------------------------
    #  App Engine Playback Server (playback_server) can be only one instance. This is different from App Engine (where application_engine_configuration is a list and you can deploy multiple instances).
    #-----------------------------------------------------------------------
    playback_server:
      admin_secret_name: playback-server-admin-secret
      admin_user: <your default administrator ID>
      images:
        db_job:
          repository: cp.icr.io/cp/cp4a/bas/solution-server-helmjob-db
          tag: 20.0.1
        solution_server:
          repository: cp.icr.io/cp/cp4a/bas/solution-server
          tag: 20.0.1
      hostname: <your app engine playback server host name>
      port: 443
      database:
        host: <database host name>
        # The database provided should be created by the App Engine Playback Server SQL script template.
        name: <database name>
        port: <database port>
        # If you want to enable database ACR for HADR, configure alternative_host and alternative_port. Otherwise, leave them blank.
        alternative_host:
        alternative_port:
        type: db2

  ## Resource Registry Configuration
  ## Important: if you've already configured Resource Registry, you don't need to change the resource_registry_configuration section in your copy of the template custom resource YAML file.
  resource_registry_configuration:
    admin_secret_name: resource-registry-admin-secret
    images:
      resource_registry:
        repository: cp.icr.io/cp/cp4a/bas/dba-etcd
        tag: 20.0.1
    hostname: <your external resource registry host name>
    port: 443
