###############################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2020. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: icp4a.ibm.com/v1
kind: ICP4ACluster
metadata:
  name: workstreams
  labels:
    app.kubernetes.io/instance: ibm-dba
    app.kubernetes.io/managed-by: ibm-dba
    app.kubernetes.io/name: ibm-dba
    release: 20.0.1
spec:
  appVersion: 20.0.1
  ## TIPS: The names of all variables in the spec field are converted to snake_case by the operator before running ansible
  ## For example, serviceAccount in the spec becomes service_account in ansible.
  ## It is recommended that you perform some type validation in Ansible on the variables to ensure that
  ## your application is receiving expected input.
  ## shared configuration among all tribe
  shared_configuration:
    sc_deployment_patterns: workstreams
    sc_deployment_type: demo
    sc_deployment_platform: OCP
    sc_deployment_hostname_suffix: "{{ meta.name }}"
    storage_configuration:
      sc_dynamic_storage_classname: ""
    root_ca_secret: "{{ meta.name }}-root-ca"
    image_pull_secrets:
    - image-pull-secret
    images:
      keytool_job_container:
        repository: cp.icr.io/cp/cp4a/ums/dba-keytool-jobcontainer
        tag: 20.0.1
      dbcompatibility_init_container:
        repository: cp.icr.io/cp/cp4a/aae/dba-dbcompatibility-initcontainer
        tag: 20.0.1
      keytool_init_container:
        repository: cp.icr.io/cp/cp4a/ums/dba-keytool-initcontainer
        tag: 20.0.1
      umsregistration_initjob:
        repository: cp.icr.io/cp/cp4a/aae/dba-umsregistration-initjob
        tag: 20.0.1
      db2u_tools:
        repository: docker.io/ibmcom/db2u.tools
        tag: 11.5.1.0-CN1
      db2:
        repository: docker.io/ibmcom/db2
        tag: 11.5.1.0-CN1
      db2_auxiliary:
        repository: docker.io/ibmcom/db2u.auxiliary.auth
        tag: 11.5.1.0-CN1
      db2_init:
        repository: docker.io/ibmcom/db2u.instdb
        tag: 11.5.1.0-CN1
      db2_etcd:
        repository: quay.io/coreos/etcd
        tag: v3.3.10
      openldap:
        repository: osixia/openldap
        tag: 1.3.0
      busybox:
        repository: docker.io/library/busybox
        tag: latest

  ########################################################################
  ########      IBM FileNet Content Manager configuration         ########
  ########################################################################
  ecm_configuration:
    cpe:
      image:
        repository: cp.icr.io/cp/cp4a/fncm/cpe
        tag: ga-554-p8cpe-if001
    cmis:
      image:
        repository: cp.icr.io/cp/cp4a/fncm/cmis
        tag: ga-304-cmis-if010
  ########################################################################
  ########   IBM Business Automation Navigator configuration      ########
  ########################################################################
  navigator_configuration:
    image:
      repository: cp.icr.io/cp/cp4a/ban/navigator-sso
      tag: ga-307-icn-if002
  ########################################################################
  ########   IBM User and Group Management Service configuration  ########
  ########################################################################
  ums_configuration:
    teamserver:
      admingroup: P8Administrators
    images:
      ums:
        repository: cp.icr.io/cp/cp4a/ums/ums
        tag: 20.0.1
  ########################################################################
  ########   IBM Application Engine configuration      ########
  ########################################################################
  application_engine_configuration:
  - name: workspace
    images:
      db_job:
        repository: cp.icr.io/cp/cp4a/aae/solution-server-helmjob-db
        tag: 20.0.1
      solution_server:
        repository: cp.icr.io/cp/cp4a/aae/solution-server
        tag: 20.0.1
  ########################################################################
  ########      IBM Resource Registry configuration               ########
  ########################################################################
  resource_registry_configuration:
    images:
      resource_registry:
        repository: cp.icr.io/cp/cp4a/aae/dba-etcd
        tag: 20.0.1
  ########################################################################
  ########   IBM Workstream Server configuration  ########
  ########################################################################
  iaws_configuration:
  - name: instance1
    iaws_server:
      image:
        repository: cp.icr.io/cp/cp4a/iaws/iaws-server
        tag: 20.0.1
      pfs_bpd_database_init_job:
        repository: cp.icr.io/cp/cp4a/iaws/pfs-bpd-database-init-prod
        tag: "20.0.1"
      upgrade_job:
        repository: cp.icr.io/cp/cp4a/iaws/iaws-server-dbhandling
        tag: "20.0.1"
      ibm_workplace_job:
        repository: cp.icr.io/cp/cp4a/iaws/iaws-ibm-workplace
        tag: "20.0.1"
      content_integration:
        init_job_image:
          repository: cp.icr.io/cp/cp4a/iaws/iaws-ps-content-integration
          tag: "20.0.1"
      jms:
        image:
          repository: cp.icr.io/cp/cp4a/iaws/jms
          tag: "20.0.1"
  ########################################################################
  ########   IBM Process Federation Server configuration  ########
  ########################################################################
  pfs_configuration:
    pfs:
      image:
        repository: cp.icr.io/cp/cp4a/iaws/pfs-prod
        tag: "20.0.1"
    elasticsearch:
      es_image:
        repository: cp.icr.io/cp/cp4a/iaws/pfs-elasticsearch-prod
        tag: "20.0.1"
      pfs_init_image:
        repository: cp.icr.io/cp/cp4a/iaws/pfs-init-prod
        tag: "20.0.1"
      nginx_image:
        repository: cp.icr.io/cp/cp4a/iaws/pfs-nginx-prod
        tag: "20.0.1"
