###############################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2020. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: icp4a.ibm.com/v1
kind: ICP4ACluster
metadata:
  name: bai-demo
  labels:
    app.kubernetes.io/instance: ibm-dba
    app.kubernetes.io/managed-by: ibm-dba
    app.kubernetes.io/name: ibm-dba
    release: 20.0.1
spec:
  appVersion: 20.0.1

  shared_configuration:
    sc_deployment_type: "production"  ### Possible values are "production" , "non-production"

  bai_configuration:
    imageCredentials:
      imagePullSecret: <PULL_SECRET>

    persistence:
      useDynamicProvisioning: true

    flinkPv:
      storageClassName: "<RWX_STORAGE_CLASS>"

    kafka:
      bootstrapServers: "kafka.bootstrapserver1.hostname:9092,kafka.bootstrapserver2.hostname:9092,kafka.bootstrapserver3.hostname:9092"
      securityProtocol: "PLAINTEXT"

    # settings:
    #   egress: true
    #   ingressTopic: ibm-bai-ingress
    #   egressTopic: ibm-bai-egress
    #   serviceTopic: ibm-bai-service

    setup:
      image:
        repository: <DOCKER_REGISTRY>/bai-setup

    admin:
      image:
        repository: <DOCKER_REGISTRY>/bai-admin

    flink:
      initStorageDirectory: true
      image:
        repository: <DOCKER_REGISTRY>/bai-flink
      zookeeper:
        image:
          repository: <DOCKER_REGISTRY>/bai-flink-zookeeper

    ingestion:
      install: false
      image:
        repository: <DOCKER_REGISTRY>/bai-ingestion

    adw:
      install: false
      image:
        repository: <DOCKER_REGISTRY>/bai-adw

    bpmn:
      install: false
      image:
        repository: <DOCKER_REGISTRY>/bai-bpmn

    bawadv:
      install: false
      image:
        repository: <DOCKER_REGISTRY>/bai-bawadv

    icm:
      install: false
      image:
        repository: <DOCKER_REGISTRY>/bai-icm

    odm:
      install: false
      image:
        repository: <DOCKER_REGISTRY>/bai-odm

    content:
      install: false
      image:
        repository: <DOCKER_REGISTRY>/bai-content

    initImage:
      image:
        repository: <DOCKER_REGISTRY>/bai-init

    elasticsearch:
      install: true

    ibm-dba-ek:
      image:
        imagePullPolicy: Always
        imagePullSecret: <PULL_SECRET>

      elasticsearch:
        image:
          repository: <DOCKER_REGISTRY>/bai-elasticsearch
        init:
          image:
            repository: <DOCKER_REGISTRY>/bai-init
        data:
          storage:
            persistent: true
            useDynamicProvisioning: true
            storageClass: "<RWO_STORAGE_CLASS>"
          snapshotStorage:
            enabled: true
            useDynamicProvisioning: true
            storageClassName: "<RWX_STORAGE_CLASS>"

      kibana:
        image:
          repository: <DOCKER_REGISTRY>/bai-kibana
        init:
          image:
            repository: <DOCKER_REGISTRY>/bai-init
