# This is a customized values.yaml sample.
# In this sample, only the BPMN event processing is enabled.

persistence:
  useDynamicProvisioning: true

imagePullPolicy: IfNotPresent

kafka:
  bootstrapServers: "kafka-release-cp-kafka-headless:9092"
  securityProtocol: "PLAINTEXT"

elasticsearch:
  install: true

settings:
  egress: false
  ingressTopic: bai-release-ingress
  serviceTopic: bai-release-service


admin:
  replicas: 1
  serviceType: NodePort
  externalPort: 31100

# don't install ICM event processing
icm:
  install: false

# don't install ODM event processing
odm:
  install: false

# don't install BAWAdv event processing
bawadv:
  install: false

# don't install Content event processing
content:
  install: false

ingestion:
  install: false

# Overall, the event processing is installed only for BPMN.

ibm-dba-ek:
  elasticsearch:
    data:
      storage:
        persistent: true
        useDynamicProvisioning: true
        storageClass: "bai-ek-data"
      client:
        serviceType: NodePort
        externalPort: 31200
  kibana:
    serviceType: NodePort
    externalPort: 31501
