apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  annotations:
    kubernetes.io/description: "This policy allows pods to run with
      any UID and GID, but preventing access to the host."
  name: baca-psp
spec:
  allowPrivilegeEscalation: false
  fsGroup:
    ranges:
    - max: 1
      min: 0
    rule: MustRunAs
    #rule: RunAsAny
  requiredDropCapabilities:
  - ALL
  allowedCapabilities:
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    ranges:
    - max: 1
      min: 0
    rule: MustRunAs
    #rule: RunAsAny
  volumes:
  - configMap
  - emptyDir
  - projected
  - secret
  - downwardAPI
  - persistentVolumeClaim
  forbiddenSysctls:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
  name: baca-role
rules:
- apiGroups:
  - extensions
  resourceNames:
  - baca-psp
  resources:
  - podsecuritypolicies
  #verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]
  verbs:
  - use
